import { getServerSession } from "next-auth";
import { Toaster } from 'react-hot-toast';
import { authOptions } from "./api/auth/[...nextauth]/route";
import ClientSessionProvider from "./components/context/ClientSessionProvider";
import Footer from "./components/footer/Footer";
import Navbar from './components/navbar/Navbar2';
import "./globals.css";

export const metadata = {
  title: "RPL",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <Toaster position="top-right" reverseOrder={false} />
        <ClientSessionProvider session={session}>
          <Navbar />
          {children}
          <Footer />
        </ClientSessionProvider>
      </body>
    </html>
  );
}
